### ISSUE TITLE
SDK examples for order creation

### ISSUE THREAD

**Issue by amzoyang** [InjectiveLabs/docs#3]
The current docs only describe the order message format/order types but don't provide easy code examples that developers can follow to create orders/place trades. 

It would be helpful to provide side-by-side code snippets from the Injective-SDK to allow the trader to easily to do this. 

See docs.dydx.exchange for a good example of this.

**Comment by gorgos** [comment]
Added order examples in https://github.com/InjectiveLabs/docs/commit/2d86b749729c9c673680c5352f6271485001e1fb. SDK still needs to be updated and also we need a plan/design for the SDK before giving concrete examples, so I'll leave this issue open to keep track of it.
